### ISSUE TITLE
Explain actions/checkout for forked PRs vs normal PRs

### ISSUE THREAD

**Issue by alldoami** [imjohnbo/ok-to-test#13]
Hi! I'm having trouble understanding how to get forked PRs to checkout the code of the head SHA of the PR because when I use your example code of:
```
ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
```
The `Integration Tests` come back as having succeeded, but the individual tests say they are still pending. In the Github Actions UI, it says that the tests for the forked branches are skipped even though all the criteria pass. Here is my integration file for my open source repo: https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/.github/workflows/integration.yml. I took out the above line because it didn't seem to be running the most recent commit on my PR. Any advice?

**Comment by alldoami** [comment]
For example, after I do the `ok-to-test` command, this happens: https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/373/checks?check_run_id=1658107839 which is unclear on what has passed since it doesn't specify the individual tests we want. But when I go to Github actions it _seems_ like it runs the tests but it doesn't get reflected in the PR.

**Comment by imjohnbo** [comment]
Hi @alldoami! Did you get it working?

I'll refer to my code since I know it best. If a pull request from a fork has 5 commits on it and its latest SHA is 6b68bf0, I can  type `/ok-to-test sha=6b68bf0` on the pull request. That will set of the chain of events that leads here:

https://github.com/imjohnbo/ok-to-test/blob/1b4bf926f1c3ed5b945803742a455d6b18529b53/.github/workflows/integration.yml#L22-L34

which checks out the merge commit, because I want to test what would happen if 6b68bf0 was merged with my base. Note that the following line is important, because it's what checks that I'm merging what I expect to (6b68bf0):

https://github.com/imjohnbo/ok-to-test/blob/1b4bf926f1c3ed5b945803742a455d6b18529b53/.github/workflows/integration.yml#L27

> The `Integration Tests` come back as having succeeded, but the individual tests say they are still pending. In the Github Actions UI, it says that the tests for the forked branches are skipped even though all the criteria pass.

Interesting, I haven't seen this one before!
