### ISSUE TITLE
See explicit logs in original workflow run 

### ISSUE THREAD

**Issue by Wxl19980214** [imjohnbo/ok-to-test#17]
@imjohnbo hello, we have applied your template in our repo, yet there is some functionality we want cannot be achieved. So we would like to hear some insights from you. So basically we would like to see the logs in the original workflow instead of the /ok-to-test command workflow for a forked-based pull request. For example, if you look [here](https://github.com/ploomber/ploomber/runs/6940199759?check_suite_focus=true) It says the check is skipped. Let's say the owner triggered the /ok-to-test workflow and it fails, here it will only display the check fails. The real logs are displayed in the newly triggered /ok-to-test workflow. So what we want is that right here in the original workflow we can see the error log, or at least can display an url pointing to the actual running workflow. Do you think this is achievable? Thanks

**Comment by Wxl19980214** [comment]
Hi @imjohnbo, I am sorry we forgot to comment /ok-to-test. If you take a look at this PR(https://github.com/ploomber/ploomber/pull/866) , you will see tests such as 
Integration tests / Windows-integration-forked (pull_request), and if you click detail, it is marked as cancelled. But the /ok-to-test command has triggered a new workflow [here](https://github.com/ploomber/ploomber/actions/runs/2569902658) and it is failing. What we want is that the log information in the failed workflow can be somehow passed into the original one. So when we click on details in the PR, we see the log error. Do you think this is achievable? Thanks a lot!  :  )

**Comment by imjohnbo** [comment]
Would you mind starting fresh from an up to date fork? I think some wires are getting crossed between your old style of `ci-integration.yml`, PR'd from [your fork](https://github.com/Wxl19980214/ploomber/blob/ok-to-test-issue-branch/.github/workflows/ci-integration.yml), and the new style of `ci-integration-PLATFORM`, introduced after your fork was made. 🙏

**Comment by Wxl19980214** [comment]
Yes. I have recreate the scenario: here is the PR (https://github.com/ploomber/ploomber/pull/887) and you will see it fails on all forked integration tests like this: MacOS integration tests / Macos-integration-forked (pull_request) . But if you click on the details [here](https://github.com/ploomber/ploomber/runs/7116768949?check_suite_focus=true) it only tells me this check failed. The actual log is in a new workflow [here](https://github.com/ploomber/ploomber/runs/7116797622?check_suite_focus=true). We would like to somehow be able to see the logs in the original workflow, is this something achievable? Thanks!

**Comment by imjohnbo** [comment]
I see now, thanks for reproducing. Yeah, it'd be nice to associate [this grouping](https://github.com/ploomber/ploomber/actions/runs/2584604184) (`check suite` or `check run` or `workflow run`? I've lost the thread after a couple of years) with [the PR](https://github.com/ploomber/ploomber/pull/887). I thought it might be a complication with `matrix` builds, but I reproduced it with one environment builds too.

I'm going to consider this an https://github.com/imjohnbo/ok-to-test/labels/enhancement since the core functionality of using secrets in actions from forked PRs works. As a workaround, we're still able to navigate to the overview like [this](https://github.com/ploomber/ploomber/actions/runs/2584604184) through the Actions logs.

Contributions and ideas welcome!

**Comment by Wxl19980214** [comment]
Thank you anyway. I have tried multiple ways. But looks like only part of information can be passed on to the original flow! Thanks for the template, it's very useful.
