### ISSUE TITLE
Using personal access token

### ISSUE THREAD

**Issue by giswqs** [imjohnbo/ok-to-test#9]
I am using the personal access token authentication method. However, I can't seem to get it to work. Here is my [ok-to-test.yml](https://github.com/giswqs/geemap/blob/master/.github/workflows/ok-to-test.yml). What lines should be commented out in order to make it work for the personal access token? Thanks.

**Comment by giswqs** [comment]
[Here](https://github.com/giswqs/geemap/pull/183) is my test pull request. Nothing happens after the `/ok-to-test` command

![](https://i.imgur.com/9WAUF05.png)

**Comment by imjohnbo** [comment]
Hi @giswqs, thanks for the question. Using a PAT is just fine.

Instead, I think my screenshot threw you off. In my example workflow (and [yours](https://github.com/giswqs/geemap/blob/master/.github/workflows/integration.yml#L25-L27)), `sha` is required to prevent a race condition security flaw. Theoretically someone could sneak in a malicious commit just after an admin types `/ok-to-test` – if that's not a concern to you, feel free to leave this section out.

See [example usage](https://github.com/imjohnbo/ok-to-test#example) for more: `/ok-to-test sha=<head-sha>`.

**Comment by giswqs** [comment]
@imjohnbo I can't get `/ok-to-test sha=<head-sha>` to work. Could you please take a look at this [pull request](https://github.com/giswqs/geemap/pull/197) and advise? Thanks.

**Comment by imjohnbo** [comment]
Hi @giswqs. Looks like this successful [check run](https://github.com/giswqs/geemap/runs/1511526878?check_suite_focus=true) came from you [typing](https://github.com/giswqs/geemap/pull/197#issuecomment-739981627) `/ok-to-test sha=33684eb`. I take that to mean your [`ok-to-test`](https://github.com/giswqs/geemap/blob/master/.github/workflows/ok-to-test.yml) and [`integration.yml`](https://github.com/giswqs/geemap/blob/master/.github/workflows/integration.yml) workflows are wired up correctly. ✅

But you have a separate workflow, [`build`](https://github.com/giswqs/geemap/blob/master/.github/workflows/build.yaml), that is also triggered on `pull_request`. I might insert the contents of that workflow [here](https://github.com/giswqs/geemap/blob/master/.github/workflows/integration.yml#L36) in order to allow pull requests coming from forks to access secrets like [your EARTHENGINE_TOKEN](https://github.com/giswqs/geemap/blob/master/.github/workflows/build.yaml#L42).

Going to close since the `ok-to-test` part seems to be working.
